# Generated by Django 3.2 on 2021-06-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudmember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('role', models.CharField(max_length=10, verbose_name='업무')),
                ('person_id1', models.CharField(max_length=6, verbose_name='주민번호 앞자리')),
                ('person_id2', models.CharField(max_length=7, verbose_name='주민번호 뒷자리')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('phone_num', models.CharField(max_length=11, verbose_name='전화번호')),
                ('entering_date', models.CharField(blank=True, max_length=10, verbose_name='입사일')),
                ('resignation_date', models.CharField(blank=True, max_length=10, verbose_name='퇴사일')),
                ('license_num', models.CharField(blank=True, max_length=30, verbose_name='면허번호')),
                ('check', models.CharField(blank=True, max_length=50, verbose_name='운행판정표')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='파일')),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_member', to='humanresource.member')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_type', models.CharField(max_length=10, verbose_name='종류')),
                ('reason', models.CharField(max_length=100, verbose_name='내용')),
                ('start_date', models.CharField(max_length=10, verbose_name='시작날짜')),
                ('finish_date', models.CharField(max_length=10, verbose_name='종료날짜')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('creator', models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='crudmember.user')),
                ('member_id', models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_member', to='humanresource.member')),
            ],
        ),
    ]
