# Generated by Django 3.1.5 on 2021-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='entering_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resignation_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='퇴사일'),
        ),
    ]
