# Generated by Django 3.1.5 on 2021-02-13 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_auto_20210213_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='date',
        ),
        migrations.AddField(
            model_name='hr',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='종료날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작날짜'),
            preserve_default=False,
        ),
    ]
