# Generated by Django 3.1.5 on 2021-05-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_auto_20210519_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='check',
            field=models.CharField(blank=True, max_length=50, verbose_name='운행판정표'),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_num',
            field=models.CharField(blank=True, max_length=30, verbose_name='면허번호'),
        ),
    ]
