# Generated by Django 3.1.5 on 2021-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0003_auto_20210519_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='person_id',
        ),
        migrations.AddField(
            model_name='member',
            name='person_id1',
            field=models.IntegerField(default=1, verbose_name='주민번호 앞자리'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='person_id2',
            field=models.IntegerField(default=1, verbose_name='주민번호 뒷자리'),
            preserve_default=False,
        ),
    ]
