# Generated by Django 3.1.5 on 2021-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0003_auto_20210213_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록날짜'),
        ),
    ]
