# Generated by Django 3.1.5 on 2021-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0004_auto_20210519_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='authority',
        ),
        migrations.AlterField(
            model_name='hr',
            name='finish_date',
            field=models.CharField(max_length=10, verbose_name='종료날짜'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='start_date',
            field=models.CharField(max_length=10, verbose_name='시작날짜'),
        ),
    ]
