# Generated by Django 3.1.5 on 2021-05-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0005_auto_20210520_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_member', to='humanresource.member'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='내용'),
        ),
    ]
