# Generated by Django 3.1.5 on 2021-05-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0006_auto_20210521_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='person_id1',
            field=models.CharField(max_length=6, verbose_name='주민번호 앞자리'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person_id2',
            field=models.CharField(max_length=7, verbose_name='주민번호 뒷자리'),
        ),
    ]
