# Generated by Django 3.1.5 on 2021-05-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0007_auto_20210523_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.CharField(max_length=11, verbose_name='전화번호'),
        ),
    ]
