# Generated by Django 3.2 on 2021-06-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, null=True, verbose_name='사용자id')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='이름')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('tel', models.IntegerField(null=True, verbose_name='폰 번호')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('authority', models.CharField(max_length=3, null=True, verbose_name='권한')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='crudmember.user')),
            ],
            options={
                'db_table': 'user_files',
            },
        ),
    ]
