# Generated by Django 3.1.4 on 2021-01-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, null=True, verbose_name='사용자id')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='이름')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('tel', models.IntegerField(null=True, verbose_name='번호')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudmember.user')),
            ],
            options={
                'db_table': 'user_files',
            },
        ),
    ]
