# Generated by Django 3.1.4 on 2021-01-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0002_auto_20210115_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='user',
            field=models.ForeignKey(db_column='user_files_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='crudmember.user'),
        ),
    ]
