# Generated by Django 3.1.4 on 2021-01-15 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0003_auto_20210115_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfiles',
            name='user',
        ),
        migrations.AddField(
            model_name='userfiles',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='crudmember.user'),
        ),
    ]
