# Generated by Django 3.1.4 on 2021-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0004_auto_20210115_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='crudmember.user'),
        ),
    ]
