# Generated by Django 3.1.4 on 2021-01-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0005_auto_20210116_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFiles',
            new_name='UserFile',
        ),
    ]
