# Generated by Django 3.1.5 on 2021-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0006_auto_20210116_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(null=True, verbose_name='폰 번호'),
        ),
    ]
