# Generated by Django 3.1.5 on 2021-02-13 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0008_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
    ]
