# Generated by Django 3.1.5 on 2021-02-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0009_userip_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userip',
            name='pub_date',
        ),
    ]
