# Generated by Django 3.1.5 on 2021-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0011_userip_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.CharField(max_length=3, null=True, verbose_name='권한'),
        ),
    ]
