# Generated by Django 3.1.5 on 2021-04-19 22:38

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudmember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('content', models.TextField(max_length=3000, verbose_name='내용')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('creator', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_user', to='crudmember.user', verbose_name='작성자')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=document.models.DocumentFile.get_file_path)),
                ('filename', models.CharField(max_length=1024, null=True, verbose_name='첨부파일명')),
                ('document_id', models.ForeignKey(db_column='document_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_file', to='document.document')),
            ],
            options={
                'db_table': 'document_file',
            },
        ),
    ]
