# Generated by Django 3.1.5 on 2021-04-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document_id',
            field=models.ForeignKey(db_column='document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_file', to='document.document'),
        ),
    ]
