# Generated by Django 3.1.4 on 2021-01-27 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='주문자 이름')),
                ('tel', models.IntegerField(verbose_name='전화번호')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_cnt', models.IntegerField(verbose_name='버스 대수')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('kinds', models.CharField(max_length=2, verbose_name='왕복or편도')),
                ('purpose', models.CharField(max_length=30, null=True, verbose_name='용도')),
                ('bus_type', models.CharField(max_length=20, null=True, verbose_name='버스종류')),
                ('requirements', models.CharField(max_length=100, null=True, verbose_name='요구사항')),
                ('people_num', models.IntegerField(verbose_name='탑승인원')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('pay_type', models.CharField(max_length=2, verbose_name='카드or현금')),
                ('order_consumer', models.ForeignKey(db_column='consumer_id', on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='dispatch.dispatchconsumer')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=50, verbose_name='출발지')),
                ('departure_date', models.DateTimeField(verbose_name='출발시간')),
                ('arrival', models.CharField(max_length=50, verbose_name='도착지')),
                ('arrival_date', models.DateTimeField(verbose_name='도착시간')),
                ('boarding_place', models.CharField(max_length=50, null=True, verbose_name='승차장소')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='route_order', to='dispatch.dispatchorder')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='info_order', to='dispatch.dispatchorder')),
            ],
        ),
    ]
