# Generated by Django 3.1.5 on 2021-04-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanresource', '0001_initial'),
        ('crudmember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='주문자 이름')),
                ('tel', models.CharField(max_length=15, verbose_name='전화번호')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=50, verbose_name='출발지')),
                ('arrival', models.CharField(max_length=50, verbose_name='도착지')),
                ('stopover', models.CharField(blank=True, max_length=100, null=True, verbose_name='경유지')),
                ('route_name', models.CharField(max_length=50, verbose_name='노선명')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_cnt', models.IntegerField(verbose_name='버스 대수')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('kinds', models.CharField(max_length=2, verbose_name='왕복or편도')),
                ('purpose', models.CharField(blank=True, max_length=30, verbose_name='용도')),
                ('bus_type', models.CharField(blank=True, max_length=20, verbose_name='버스종류')),
                ('requirements', models.CharField(blank=True, max_length=100, verbose_name='요구사항')),
                ('people_num', models.IntegerField(verbose_name='탑승인원')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('pay_type', models.CharField(max_length=2, verbose_name='카드or현금')),
                ('departure_date', models.CharField(max_length=16, verbose_name='출발시간')),
                ('arrival_date', models.CharField(max_length=16, verbose_name='도착시간')),
                ('check', models.BooleanField(default=False, verbose_name='배차완료')),
                ('consumer', models.ForeignKey(db_column='consumer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to='dispatch.dispatchconsumer')),
                ('creator', models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_creator', to='crudmember.user')),
                ('route', models.ForeignKey(db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='dispatch.dispatchroute')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connect_creator', to='crudmember.user')),
                ('driver_id', models.ForeignKey(db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_driver_id', to='humanresource.member')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='info_order', to='dispatch.dispatchorder')),
            ],
        ),
    ]
