# Generated by Django 3.1.5 on 2021-04-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=50, verbose_name='출발지')),
                ('arrival', models.CharField(max_length=50, verbose_name='도착지')),
                ('stopover', models.CharField(blank=True, max_length=100, null=True, verbose_name='경유지')),
            ],
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='stopover',
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='brief',
            field=models.CharField(default=models.CharField(max_length=16, verbose_name='출발시간'), max_length=50, verbose_name='노선명'),
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='consumer',
            field=models.ForeignKey(db_column='consumer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to='dispatch.dispatchconsumer'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='route',
            field=models.ForeignKey(db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='dispatch.dispatchroute'),
        ),
    ]
