# Generated by Django 3.1.5 on 2021-04-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchconnect',
            name='bus_id',
            field=models.ForeignKey(db_column='bus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_bus_id', to='vehicle.vehicle'),
        ),
    ]
