# Generated by Django 3.1.5 on 2021-01-31 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0006_auto_20210116_1924'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='writer',
            field=models.ForeignKey(db_column='writer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='crudmember.user'),
        ),
    ]
