# Generated by Django 3.1.5 on 2021-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_auto_20210412_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchorder',
            name='brief',
        ),
        migrations.AddField(
            model_name='dispatchroute',
            name='route_name',
            field=models.CharField(default=None, max_length=50, verbose_name='노선명'),
            preserve_default=False,
        ),
    ]
