# Generated by Django 3.1.5 on 2021-02-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatchorder_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchorder',
            old_name='order_consumer',
            new_name='consumer',
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='first_departure_date',
            field=models.DateTimeField(null=True, verbose_name='출발날짜'),
        ),
    ]
