# Generated by Django 3.1.5 on 2021-02-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20210202_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchconsumer',
            name='tel',
            field=models.CharField(max_length=15, verbose_name='전화번호'),
        ),
    ]
