# Generated by Django 3.1.5 on 2021-04-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20210412_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchconnect',
            name='check',
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='check',
            field=models.BooleanField(default=False, verbose_name='배차완료'),
        ),
    ]
