# Generated by Django 3.1.5 on 2021-06-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_auto_20210426_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchorder',
            old_name='routine',
            new_name='regularly',
        ),
    ]
