# Generated by Django 3.1.5 on 2021-02-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_auto_20210207_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False, verbose_name='배차완료')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='info_order', to='dispatch.dispatchorder')),
            ],
        ),
        migrations.DeleteModel(
            name='DispatchInfo',
        ),
    ]
