# Generated by Django 3.1.5 on 2021-07-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_auto_20210616_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchorder',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='dispatchorder',
            name='people_num',
        ),
    ]
