# Generated by Django 3.1.5 on 2021-07-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_auto_20210701_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularlyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='그룹 이름')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='거래처')),
            ],
        ),
        migrations.RemoveField(
            model_name='dispatchconsumer',
            name='company',
        ),
        migrations.AddField(
            model_name='dispatchroute',
            name='regularly_group',
            field=models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularly_route', to='dispatch.regularlygroup'),
        ),
    ]
