# Generated by Django 3.1.5 on 2021-02-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0011_userip_pub_date'),
        ('dispatch', '0005_auto_20210210_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchorder',
            name='writer',
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_creator', to='crudmember.user'),
        ),
    ]
