# Generated by Django 3.1.5 on 2021-07-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_auto_20210701_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchorder',
            name='route',
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='arrival',
            field=models.CharField(default='no', max_length=50, verbose_name='도착지'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='departure',
            field=models.CharField(default='no', max_length=50, verbose_name='출발지'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='regularly_group',
            field=models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularly_route', to='dispatch.regularlygroup'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='route_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='노선명'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='stopover',
            field=models.CharField(blank=True, max_length=100, verbose_name='경유지'),
        ),
        migrations.AlterField(
            model_name='regularlygroup',
            name='company',
            field=models.CharField(blank=True, default='no', max_length=20, verbose_name='거래처'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DispatchRoute',
        ),
    ]
