# Generated by Django 3.1.5 on 2021-02-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0004_auto_20210213_2012'),
        ('dispatch', '0006_auto_20210213_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchconnect',
            name='driver_id',
            field=models.ForeignKey(db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_driver_id', to='humanresource.member'),
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='first_departure_date',
            field=models.DateField(null=True, verbose_name='출발날짜'),
        ),
    ]
