# Generated by Django 3.1.5 on 2021-07-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_auto_20210706_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='regularly_group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularly_route', to='dispatch.regularlygroup'),
        ),
    ]
