# Generated by Django 3.1.5 on 2021-02-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_auto_20210225_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='brief',
            field=models.CharField(default=models.DateField(null=True, verbose_name='출발날짜'), max_length=50, verbose_name='적요'),
        ),
    ]
