# Generated by Django 3.1.5 on 2021-02-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_dispatchorder_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='brief',
            field=models.CharField(default='<django.db.models.fields.DateField>', max_length=50, verbose_name='적요'),
        ),
    ]
