# Generated by Django 3.1.5 on 2021-07-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_auto_20210706_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='driver_allowance',
            field=models.IntegerField(null=True, verbose_name='기사수당'),
        ),
    ]
