# Generated by Django 3.1.5 on 2021-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_auto_20210226_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchorder',
            name='brief',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=50, verbose_name='적요'),
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='first_departure_date',
            field=models.CharField(max_length=10, null=True, verbose_name='출발날짜'),
        ),
        migrations.AlterField(
            model_name='dispatchroute',
            name='arrival_date',
            field=models.CharField(max_length=16, verbose_name='도착시간'),
        ),
        migrations.AlterField(
            model_name='dispatchroute',
            name='departure_date',
            field=models.CharField(max_length=16, verbose_name='출발시간'),
        ),
    ]
