# Generated by Django 3.1.5 on 2021-07-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_dispatchorder_driver_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchconnect',
            name='date',
            field=models.CharField(default=1, max_length=10, verbose_name='날짜'),
            preserve_default=False,
        ),
    ]
