# Generated by Django 3.1.5 on 2021-07-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_dispatchconnect_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchorder',
            name='check',
        ),
    ]
