# Generated by Django 3.1.5 on 2021-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_auto_20210228_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchroute',
            name='arrival_date',
            field=models.CharField(max_length=30, verbose_name='도착시간'),
        ),
        migrations.AlterField(
            model_name='dispatchroute',
            name='departure_date',
            field=models.CharField(max_length=30, verbose_name='출발시간'),
        ),
    ]
