# Generated by Django 3.1.5 on 2021-02-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_auto_20210228_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchroute',
            name='arrival_date',
            field=models.CharField(max_length=100, verbose_name='도착시간'),
        ),
    ]
