# Generated by Django 3.2 on 2021-06-14 23:12

from django.db import migrations, models
import django.db.models.deletion
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanresource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_num', models.CharField(max_length=15, verbose_name='차량번호')),
                ('group', models.CharField(max_length=15, verbose_name='소속')),
                ('vehicle_type', models.CharField(max_length=15, verbose_name='차량종류')),
                ('maker', models.CharField(max_length=15, verbose_name='제조사')),
                ('model_year', models.CharField(max_length=15, verbose_name='연식')),
                ('use', models.BooleanField(default=False, verbose_name='사용여부')),
                ('passenger_num', models.IntegerField(verbose_name='승차인원')),
                ('driver', models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='humanresource.member', verbose_name='기사')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.CharField(max_length=50, verbose_name='점검날짜')),
                ('check_detail', models.CharField(max_length=500, verbose_name='점검내용')),
                ('vehicle_id', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_check',
            },
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_date', models.CharField(max_length=10, verbose_name='보험일자')),
                ('insurance_price', models.CharField(max_length=20, verbose_name='금액')),
                ('insurance_comp', models.CharField(max_length=50, verbose_name='보험회사')),
                ('expiration_date', models.CharField(max_length=10, verbose_name='만료일자')),
                ('vehicle_id', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_insurance',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_file', models.FileField(blank=True, null=True, upload_to=vehicle.models.VehicleDocument.get_file_path)),
                ('filename', models.CharField(max_length=1024, null=True, verbose_name='첨부파일명')),
                ('check_id', models.ForeignKey(db_column='check_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclecheck')),
                ('vehicle_id', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_document',
            },
        ),
    ]
