# Generated by Django 3.1.5 on 2021-02-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanresource', '0004_auto_20210213_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_num', models.CharField(max_length=15, verbose_name='차량번호')),
                ('group', models.CharField(max_length=15, verbose_name='소속')),
                ('vehicle_type', models.CharField(max_length=15, verbose_name='차량종류')),
                ('maker', models.CharField(max_length=15, verbose_name='제조사')),
                ('model_year', models.CharField(max_length=15, verbose_name='연식')),
                ('use', models.BooleanField(default=False, verbose_name='사용여부')),
                ('passenger_num', models.IntegerField(verbose_name='승차인원')),
                ('driver', models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='humanresource.member', verbose_name='기사')),
            ],
        ),
    ]
