# Generated by Django 2.2.4 on 2021-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.CharField(max_length=15, verbose_name='연식'),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='expiration_date',
            field=models.CharField(max_length=10, verbose_name='만료일자'),
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='insurance_date',
            field=models.CharField(max_length=10, verbose_name='보험일자'),
        ),
    ]
