# Generated by Django 4.0.5 on 2024-10-28 00:41

import approval.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=100, verbose_name='결제 종류')),
                ('title', models.CharField(max_length=100, verbose_name='결제 종류')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(max_length=100, verbose_name='현황')),
                ('date', models.CharField(max_length=100, verbose_name='등록일')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=approval.models.ApprovalFile.get_file_path)),
                ('filename', models.TextField(null=True, verbose_name='첨부파일명')),
                ('path', models.TextField(null=True, verbose_name='경로')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, verbose_name='순서')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='재가여부')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('approval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='approval.approval')),
            ],
        ),
    ]
