# Generated by Django 4.0.5 on 2024-08-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='next_approver_id',
        ),
        migrations.AddField(
            model_name='approver',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='재가여부'),
        ),
    ]
