# Generated by Django 4.0.5 on 2024-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_remove_approval_next_approver_id_approver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='index',
            field=models.IntegerField(default=1, verbose_name='순서'),
        ),
    ]
