# Generated by Django 4.0.5 on 2024-08-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approver_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='date',
            field=models.CharField(default='', max_length=100, verbose_name='등록일'),
            preserve_default=False,
        ),
    ]
