# Generated by Django 3.1.5 on 2021-04-06 00:19

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudmember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('content', models.TextField(max_length=3000, verbose_name='내용')),
                ('kinds', models.CharField(max_length=10, null=True, verbose_name='종류')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('creator', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='crudmember.user', verbose_name='작성자')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='NoticeViewCnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='조회시간')),
                ('notice_id', models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, to='notice.notice')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='crudmember.user', verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=notice.models.NoticeFile.get_file_path)),
                ('filename', models.CharField(max_length=1024, null=True, verbose_name='첨부파일명')),
                ('notice_id', models.ForeignKey(db_column='notice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='notice.notice')),
            ],
            options={
                'db_table': 'notice_file',
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='댓글내용')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('creator', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='crudmember.user', verbose_name='작성자')),
                ('notice_id', models.ForeignKey(db_column='notice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='notice.notice')),
            ],
            options={
                'db_table': 'notice_comment',
            },
        ),
    ]
