# Generated by Django 3.1.4 on 2021-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudmember', '0005_auto_20210116_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('content', models.TextField(max_length=3000, verbose_name='내용')),
                ('types', models.CharField(max_length=10, null=True, verbose_name='종류')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('creator', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='crudmember.user', verbose_name='작성자')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='NoticeFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('notice_id', models.ForeignKey(db_column='notice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='notice.notice')),
            ],
            options={
                'db_table': 'notice_files',
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='댓글내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('creator', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='crudmember.user', verbose_name='작성자')),
                ('notice_id', models.ForeignKey(db_column='notice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='notice.notice')),
            ],
        ),
    ]
