# Generated by Django 3.1.4 on 2021-01-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticeFiles',
            new_name='NoticeFile',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='types',
            new_name='type',
        ),
    ]
