# Generated by Django 3.1.5 on 2021-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='view_cnt',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
