# Generated by Django 3.1.4 on 2021-01-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/notice/%Y/%m/%d'),
        ),
    ]
