# Generated by Django 3.1.5 on 2021-04-19 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0001_initial'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='creator',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notice_user', to='crudmember.user', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='noticefile',
            name='notice_id',
            field=models.ForeignKey(db_column='notice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_file', to='notice.notice'),
        ),
    ]
