# Generated by Django 3.1.4 on 2021-01-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20210116_1924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticecomment',
            table='notice_comment',
        ),
        migrations.AlterModelTable(
            name='noticefile',
            table='notice_file',
        ),
    ]
