# Generated by Django 3.1.5 on 2021-05-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_view_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='num',
            field=models.IntegerField(default=0, verbose_name='번호'),
        ),
    ]
