# Generated by Django 3.1.4 on 2021-01-22 23:51

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20210122_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.NoticeFile.get_file_path),
        ),
    ]
