# Generated by Django 3.1.4 on 2021-01-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20210116_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='type',
            new_name='kinds',
        ),
    ]
