# Generated by Django 3.1.4 on 2021-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20210122_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticefile',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
    ]
