# Generated by Django 3.1.5 on 2021-05-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticecomment',
            name='content',
            field=models.TextField(max_length=200, verbose_name='댓글내용'),
        ),
    ]
