# Generated by Django 3.1.4 on 2021-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_noticefile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticefile',
            name='filename',
            field=models.CharField(max_length=1024, null=True, verbose_name='첨부파일명'),
        ),
    ]
