# Generated by Django 3.1.4 on 2021-01-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20210116_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='registered_dttm',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='noticecomment',
            old_name='registered_dttm',
            new_name='pub_date',
        ),
    ]
