# Generated by Django 3.1.4 on 2021-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20210124_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hits',
            field=models.IntegerField(max_length=100, null=True, verbose_name='조회수'),
        ),
        migrations.DeleteModel(
            name='NoticeViewCnt',
        ),
    ]
