# Generated by Django 3.1.4 on 2021-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20210124_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='hits',
            field=models.IntegerField(null=True, verbose_name='조회수'),
        ),
    ]
