# Generated by Django 3.1.4 on 2021-01-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudmember', '0006_auto_20210116_1924'),
        ('notice', '0008_auto_20210124_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='hits',
        ),
        migrations.CreateModel(
            name='NoticeViewCnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='조회시간')),
                ('notice_id', models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, to='notice.notice')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='crudmember.user', verbose_name='작성자')),
            ],
        ),
    ]
