# Generated by Django 3.1.5 on 2021-04-15 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudmember', '0001_initial'),
        ('humanresource', '0001_initial'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=30, verbose_name='적요')),
                ('collect_date', models.CharField(max_length=10, null=True, verbose_name='수금일자')),
                ('check', models.BooleanField(default=False, verbose_name='입금확인')),
                ('remark', models.CharField(max_length=50, null=True, verbose_name='비고')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('connect_id', models.ForeignKey(db_column='connect_id', on_delete=django.db.models.deletion.CASCADE, related_name='collect_connect', to='dispatch.dispatchconnect')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collect_user', to='crudmember.user')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(verbose_name='기본급')),
                ('bonus', models.IntegerField(verbose_name='상여금')),
                ('additional', models.IntegerField(verbose_name='추가금')),
                ('deductible', models.IntegerField(verbose_name='공제금')),
                ('total', models.IntegerField(verbose_name='총금액')),
                ('payment_month', models.CharField(default='2021-04', max_length=7, verbose_name='지급월')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_user', to='crudmember.user')),
                ('member_id', models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_monthly', to='humanresource.member')),
            ],
        ),
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(max_length=10, verbose_name='지급구분')),
                ('brief', models.CharField(max_length=30, verbose_name='적요')),
                ('price', models.IntegerField(verbose_name='지출금액')),
                ('outlay_date', models.CharField(max_length=10, verbose_name='지출일자')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlay_user', to='crudmember.user')),
                ('salary_id', models.ForeignKey(blank=True, db_column='salary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlay_salary', to='accounting.monthlysalary')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(default='기타', max_length=30, verbose_name='수입구분')),
                ('brief', models.CharField(max_length=30, verbose_name='적요')),
                ('price', models.IntegerField(verbose_name='수입금액')),
                ('income_date', models.CharField(max_length=10, verbose_name='수입일자')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('collect_id', models.ForeignKey(db_column='collect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_collect', to='accounting.collect')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_user', to='crudmember.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(blank=True, verbose_name='상여금')),
                ('additional', models.IntegerField(blank=True, verbose_name='추가금')),
                ('date', models.CharField(default=datetime.datetime.now, max_length=10, verbose_name='날짜')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('connect_id', models.ForeignKey(blank=True, db_column='connect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily_connect', to='dispatch.dispatchconnect')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_daily_user', to='crudmember.user')),
                ('monthly_salary', models.ForeignKey(db_column='monthly_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily', to='accounting.monthlysalary')),
            ],
        ),
    ]
