# Generated by Django 3.1.5 on 2021-02-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanresource', '0004_auto_20210213_2012'),
        ('dispatch', '0006_auto_20210213_1544'),
        ('crudmember', '0012_user_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=30, verbose_name='적요')),
                ('collect_date', models.DateField(null=True, verbose_name='수금일자')),
                ('check', models.BooleanField(default=False, verbose_name='입금확인')),
                ('remark', models.CharField(max_length=50, verbose_name='비고')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='collect_order', to='dispatch.dispatchorder')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(verbose_name='기본급')),
                ('bonus', models.IntegerField(verbose_name='상여금')),
                ('additional', models.IntegerField(verbose_name='추가금')),
                ('deductible', models.IntegerField(verbose_name='공제금')),
                ('total', models.IntegerField(verbose_name='총금액')),
                ('payment_date', models.DateField(verbose_name='지급일')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('edit_date', models.DateTimeField(auto_now_add=True, verbose_name='수정시간')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_user', to='crudmember.user')),
                ('member_id', models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_member', to='humanresource.member')),
            ],
        ),
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(max_length=10, verbose_name='지급구분')),
                ('brief', models.CharField(max_length=30, verbose_name='적요')),
                ('price', models.IntegerField(verbose_name='지출금액')),
                ('outlay_date', models.DateField(verbose_name='지출일자')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlay_user', to='crudmember.user')),
                ('salary_id', models.ForeignKey(db_column='salary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlay_salary', to='accounting.salary')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(max_length=30, verbose_name='수입구분')),
                ('brief', models.CharField(max_length=30, verbose_name='적요')),
                ('price', models.IntegerField(verbose_name='수입금액')),
                ('income_date', models.DateField(verbose_name='수입일자')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('collect_id', models.ForeignKey(db_column='collect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_collect', to='accounting.collect')),
                ('creator', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_user', to='crudmember.user')),
            ],
        ),
    ]
