# Generated by Django 3.1.5 on 2021-02-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='daily_salary',
        ),
        migrations.AddField(
            model_name='dailysalary',
            name='monthly_salary',
            field=models.ForeignKey(db_column='monthly_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_monthly', to='accounting.monthlysalary'),
        ),
    ]
