# Generated by Django 3.1.5 on 2021-02-28 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_auto_20210228_2218'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalary',
            name='order_id',
        ),
        migrations.AddField(
            model_name='dailysalary',
            name='connect_id',
            field=models.ForeignKey(blank=True, db_column='connect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily_connect', to='dispatch.dispatchconnect'),
        ),
    ]
