# Generated by Django 3.1.5 on 2021-04-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='connect_id',
            field=models.ForeignKey(db_column='connect_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collect_connect', to='dispatch.dispatchconnect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysalary',
            name='connect_id',
            field=models.ForeignKey(blank=True, db_column='connect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily_connect', to='dispatch.dispatchconnect'),
        ),
    ]
