# Generated by Django 3.1.5 on 2021-02-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210222_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='monthly_salary',
            field=models.ForeignKey(db_column='monthly_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_monthly', to='accounting.monthlysalary'),
        ),
    ]
