# Generated by Django 3.1.5 on 2021-05-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210502_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='total',
            field=models.IntegerField(blank=True, default=100, verbose_name='총금액'),
            preserve_default=False,
        ),
    ]
