# Generated by Django 3.1.5 on 2021-02-25 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0004_auto_20210213_2012'),
        ('accounting', '0003_auto_20210222_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='payment_month',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='지급월'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysalary',
            name='additional',
            field=models.IntegerField(blank=True, verbose_name='추가금'),
        ),
        migrations.AlterField(
            model_name='dailysalary',
            name='bonus',
            field=models.IntegerField(blank=True, verbose_name='상여금'),
        ),
        migrations.AlterField(
            model_name='dailysalary',
            name='monthly_salary',
            field=models.ForeignKey(db_column='monthly_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily', to='accounting.monthlysalary'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_monthly', to='humanresource.member'),
        ),
    ]
