# Generated by Django 3.1.5 on 2021-02-25 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210225_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='작성시간'),
        ),
    ]
