# Generated by Django 3.1.5 on 2021-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_dailysalary_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='비고'),
        ),
    ]
