# Generated by Django 3.1.5 on 2021-05-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_dailysalary_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='goyong',
            field=models.IntegerField(default=0, verbose_name='고용보험'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='gukmin',
            field=models.IntegerField(default=0, verbose_name='국민연금'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='gungang',
            field=models.IntegerField(default=0, verbose_name='건강보험'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='income_tax',
            field=models.IntegerField(default=0, verbose_name='소득세'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='resident_tax',
            field=models.IntegerField(default=0, verbose_name='주민세'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='zanggi',
            field=models.IntegerField(default=0, verbose_name='장기요양보험'),
        ),
    ]
