# Generated by Django 3.1.5 on 2021-02-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_auto_20210213_1544'),
        ('accounting', '0005_dailysalary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily_order', to='dispatch.dispatchorder'),
        ),
    ]
