# Generated by Django 3.1.5 on 2021-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0008_auto_20210523_2259'),
        ('accounting', '0006_auto_20210512_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_monthly', to='humanresource.member'),
        ),
    ]
