# Generated by Django 3.1.5 on 2021-02-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_auto_20210226_2314'),
        ('accounting', '0006_dailysalary_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_daily_order', to='dispatch.dispatchorder'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_month',
            field=models.DateField(default='2021-02', verbose_name='지급월'),
        ),
    ]
