# Generated by Django 3.1.5 on 2021-06-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20210524_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_month',
            field=models.CharField(default='2021-06', max_length=7, verbose_name='지급월'),
        ),
    ]
