# Generated by Django 3.1.5 on 2021-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20210226_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_month',
            field=models.CharField(default='2021-02-26', max_length=7, verbose_name='지급월'),
        ),
    ]
