# Generated by Django 3.1.5 on 2021-07-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20210616_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_month',
            field=models.CharField(default='2021-07', max_length=7, verbose_name='지급월'),
        ),
    ]
