# Generated by Django 3.1.5 on 2021-02-27 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20210226_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='date',
            field=models.CharField(default=datetime.datetime.now, max_length=10, verbose_name='작성시간'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_month',
            field=models.CharField(default='2021-02', max_length=7, verbose_name='지급월'),
        ),
    ]
