# Generated by Django 3.1.5 on 2021-02-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20210227_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalary',
            name='dispatch_id',
        ),
    ]
